domain_url: https://finolifilms.com/

collections:
  trabajos:
    output: true
    
defaults:
  - scope:
      path: ""
      type: trabajos
    values:
      layout: trabajo
      list: true
      recent: false
